#!/usr/bin/env bash
# the script that displays numbers from 1 to 100, "Fizz" for multiples of 3,
#+ "Buzz" for multiples of 5, and "FizzBuzz" for multiples of 3 and 5

for (( n=1; n < 101; n++ ))
do
    if (( n % 15 == 0 )); then
	echo "FizzBuzz"

    elif (( n % 3 == 0 )); then
	echo "Fizz"

    elif (( n % 5 == 0 )); then
	echo "Buzz"

    else
	echo "$n"
    fi
done
