#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes
#+ Displays hours: 0-12, minutes 1-59

hr=0
while [ "$hr" -le 12 ]
do
	echo "Hour: $hr"
	(( hr++ ))

	min=1
	while [ "$min" -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
done
